<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
	<meta name="description" content="best hotel in 
Missouri">
	<meta name="viewport" content="width=device-width, initial-
scare=1">
	<link rel="stylesheet" href="hotelstyle.css">
	<link rel="sytlesheet" href="slider.css">
	<link rel="stylesheet" href=
"http://code.jquery.com/ui/1.12.0/themes/smoothnews/jquery-ui.css">
<title><?php echo $page_title; ?></title>
</head>
<body>
	<a href = "home.php"><img id = "logo" src = "likestayhotel.png" alt
= "Like stay hotel logo"></a>
	<span id = "phone">PH: 1(800) 123-4567</span>
	<nav>
  <ul>
	 <li><a href="home.php">Home</a></li>
	 <li><a href="reservation.php">Reservation</a></li>
	 <li><a href="testimonials.php">Testimonials</a></li>
	 <li><a href="about.php">About</a></li>
  </ul>
 </nav>  